import { Router } from 'express';
import { authenticate } from '../middleware/authMiddleware';
import { roleGuard } from '../middleware/roleGuard';
import { validateBody } from '../utils/validators';
import * as schema from '../utils/logisticsValidation';
import * as logistics from '../controllers/logisticsController';
import { askAssistant, assistantStatus } from '../controllers/assistantController';
const router = Router();
router.use(authenticate, roleGuard('authority', 'admin'));
router.get('/', logistics.getLogistics);
router.post('/storage', validateBody(schema.storageSchema), logistics.createStorage);
router.post('/storage/link', validateBody(schema.bindStorageSchema), logistics.bindStorage);
router.post('/needs', validateBody(schema.needSchema), logistics.createNeed);
router.get('/needs/:id/suggestions', logistics.getSuggestions);
router.post('/transfers', validateBody(schema.reserveSchema), logistics.reserveTransfer);
router.patch('/transfers/:id', validateBody(schema.transitionSchema), logistics.transitionTransfer);
router.post('/consume', validateBody(schema.consumeSchema), logistics.consumeStock);
router.get('/assistant', assistantStatus);
router.post('/assistant', validateBody(schema.assistantSchema), askAssistant);
export default router;
